#!/bin/sh
# gen_stress_200.sh -- emit a 201-node DAG to stdout.
#
# Topology (a wide tree that fans out, then funnels back in, then
# trails into a deep linear chain):
#
#   L0:  4 generators  (50 packets each, 5 ms)
#   L1: 16 transforms  (each L0 fans to 4)
#   L2: 64 filters     (each L1 fans to 4; needle "-" matches all)
#   L3: 64 transforms  (1:1 with L2)
#   L4: 16 transforms  (4 L3 funnel into each L4 on ports 0..3)
#   L5:  4 batchers    (4 L4 funnel into each L5; batch 8)
#   L6:  1 uppercase   (4 L5 into ports 0..3)
#   L7: 31 transforms  (linear chain, exercises scheduler depth)
#   L8:  1 null sink
#
# Total: 4 + 16 + 64 + 64 + 16 + 4 + 1 + 31 + 1 = 201 nodes.
# Edges: 16 + 64 + 64 + 64 + 16 + 4 + 31 + 1 = 260 edges, 260 PQueues.

set -e

echo "# 10_stress_200.conf -- 201-node fan-out / fan-in / chain DAG."
echo "# Generated by examples/gen_stress_200.sh. Edit the script, not this file."
echo

# ---------- L0: generators ----------
for i in 0 1 2 3; do
    echo "g$i generator 5 50 src$i"
done
echo

# ---------- L1: 16 transforms ----------
for i in $(seq 0 15); do echo "a$i uppercase"; done
echo

# ---------- L2: 64 filters ----------
for i in $(seq 0 63); do echo "b$i filter -"; done
echo

# ---------- L3: 64 transforms ----------
for i in $(seq 0 63); do echo "c$i uppercase"; done
echo

# ---------- L4: 16 transforms (4-in joiners) ----------
for i in $(seq 0 15); do echo "d$i uppercase"; done
echo

# ---------- L5: 4 batchers (4-in joiners) ----------
for i in 0 1 2 3; do echo "e$i batch 8"; done
echo

# ---------- L6: 1 uppercase (4-in joiner) ----------
echo "f0 uppercase"
echo

# ---------- L7: 31-node linear chain ----------
for i in $(seq 0 30); do echo "h$i uppercase"; done
echo

# ---------- L8: sink ----------
echo "sink null"
echo

# ===================== edges =====================

# L0 -> L1: each generator fans to 4 transforms.
for g in 0 1 2 3; do
    base=$((g * 4))
    echo "g$g -> a$base, a$((base+1)), a$((base+2)), a$((base+3))"
done
echo

# L1 -> L2: each L1 uppercase fans to 4 filters.
for a in $(seq 0 15); do
    base=$((a * 4))
    echo "a$a -> b$base, b$((base+1)), b$((base+2)), b$((base+3))"
done
echo

# L2 -> L3: 1:1.
for i in $(seq 0 63); do echo "b$i -> c$i"; done
echo

# L3 -> L4: every 4 L3 funnel into one L4 (ports 0..3).
for d in $(seq 0 15); do
    base=$((d * 4))
    echo "c$base       -> d$d:0"
    echo "c$((base+1)) -> d$d:1"
    echo "c$((base+2)) -> d$d:2"
    echo "c$((base+3)) -> d$d:3"
done
echo

# L4 -> L5: every 4 L4 funnel into one L5 (ports 0..3).
for e in 0 1 2 3; do
    base=$((e * 4))
    echo "d$base       -> e$e:0"
    echo "d$((base+1)) -> e$e:1"
    echo "d$((base+2)) -> e$e:2"
    echo "d$((base+3)) -> e$e:3"
done
echo

# L5 -> L6: 4 L5 into f0 on ports 0..3.
echo "e0 -> f0:0"
echo "e1 -> f0:1"
echo "e2 -> f0:2"
echo "e3 -> f0:3"
echo

# L6 -> L7 -> L8: linear chain.
echo "f0 -> h0"
for i in $(seq 0 29); do echo "h$i -> h$((i+1))"; done
echo "h30 -> sink"
